### ISSUE TITLE
Not working on ESB 5.0.0

### ISSUE THREAD

**Issue by faxioman** [wso2/kubernetes-common#1]
This is the error:

```
2017-02-06T16:37:56.173051298Z 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
2017-02-06T16:37:56.173055585Z 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
2017-02-06T16:37:56.173057906Z 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
2017-02-06T16:37:56.173060110Z 	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
2017-02-06T16:37:56.173062517Z 	at org.eclipse.equinox.http.servlet.internal.Activator.registerHttpService(Activator.java:81)
2017-02-06T16:37:56.173064774Z 	at org.eclipse.equinox.http.servlet.internal.Activator.addProxyServlet(Activator.java:60)
2017-02-06T16:37:56.173066980Z 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.init(ProxyServlet.java:40)
2017-02-06T16:37:56.173069251Z 	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.init(DelegationServlet.java:38)
2017-02-06T16:37:56.173074450Z 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1282)
2017-02-06T16:37:56.173076851Z 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1195)
2017-02-06T16:37:56.173079048Z 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1085)
2017-02-06T16:37:56.173081268Z 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5318)
2017-02-06T16:37:56.173083510Z 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5610)
2017-02-06T16:37:56.173085798Z 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
2017-02-06T16:37:56.173088044Z 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1572)
2017-02-06T16:37:56.173090215Z 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1562)
2017-02-06T16:37:56.173092445Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
2017-02-06T16:37:56.173094565Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2017-02-06T16:37:56.173096748Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
2017-02-06T16:37:56.173098989Z 	at java.lang.Thread.run(Thread.java:745)
2017-02-06T16:37:56.173102768Z Caused by: java.lang.reflect.InvocationTargetException
2017-02-06T16:37:56.173107977Z 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2017-02-06T16:37:56.173110399Z 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
2017-02-06T16:37:56.173112670Z 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2017-02-06T16:37:56.173114966Z 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
2017-02-06T16:37:56.173117254Z 	at org.wso2.carbon.core.clustering.hazelcast.HazelcastClusteringAgent.initiateCustomMembershipScheme(HazelcastClusteringAgent.java:501)
2017-02-06T16:37:56.173119849Z 	... 79 more
2017-02-06T16:37:56.173122056Z Caused by: java.lang.NullPointerException
2017-02-06T16:37:56.173124191Z 	at org.wso2.carbon.membership.scheme.kubernetes.KubernetesMembershipScheme.<init>(KubernetesMembershipScheme.java:70)
2017-02-06T16:37:56.173126712Z 	... 84 more
```

Someone at wso2, reads the issues on GitHub?

**Comment by memorais** [comment]
Yup, same error here.

**Comment by memorais** [comment]
This issue is already filled in Jira:

https://www.wso2.org/jira/browse/KUBEARTFTS-6

**Comment by imesh** [comment]
Hi @faxioman and @memorais, 

Thanks for reporting this problem! I'm sorry this repository is still new and we have not done any releases here. The stable Kubernetes Artifacts including the Kubernetes membership scheme can be found at [1]. It only supports ESB 4.9.0 at the moment.

Regarding the NPE that you have encountered, it has occurred due to an issue in the Carbon Kernel. We have fixed that in the latest ESB update [1]. Please update WSO2 ESB 5.0.0 using WUM and try it out again.

[1] https://github.com/wso2/kubernetes-artifacts
[2] https://github.com/wso2/carbon-kernel/commit/9a5e1f32347342e89e8900eaf373f17145eaaf08
[3] http://wso2.com/update

**Comment by memorais** [comment]
Hello @imesh,

I will try that.

Thanks for your reply! :)

**Comment by memorais** [comment]
Hi @imesh ,

It seems that there is another issue:

```
[2017-02-17` 15:05:44,825]  INFO - KubernetesMembershipScheme Initializing kubernetes membership scheme...
[2017-02-17 15:05:44,826]  INFO - KubernetesMembershipScheme Parameter KUBERNETES_API_SERVER not found, checking KUBERNETES_SERVICE_HOST & KUBERNETES_SERVICE_PORT_HTTPS
[2017-02-17 15:05:44,827]  INFO - KubernetesMembershipScheme Kubernetes clustering configuration: [api-server] https://10.96.0.1:443 [namespace] default [services] wso2esb-manager,wso2esb-worker [skip-master-ssl-verification] true
[2017-02-17 15:05:44,929] ERROR - KubernetesMembershipScheme org.wso2.carbon.membership.scheme.kubernetes.exceptions.KubernetesMembershipSchemeException: Could not connect to Kubernetes API
[2017-02-17 15:05:44,931] ERROR - StartupFinalizerServiceComponent Cannot initialize cluster
org.apache.axis2.clustering.ClusteringFault: Kubernetes membership initialization failed
	at org.wso2.carbon.membership.scheme.kubernetes.KubernetesMembershipScheme.init(KubernetesMembershipScheme.java:169)
	at org.wso2.carbon.core.clustering.hazelcast.HazelcastClusteringAgent.initiateCustomMembershipScheme(HazelcastClusteringAgent.java:505)
	at org.wso2.carbon.core.clustering.hazelcast.HazelcastClusteringAgent.configureMembershipScheme(HazelcastClusteringAgent.java:486)
	at org.wso2.carbon.core.clustering.hazelcast.HazelcastClusteringAgent.createConfigForAxis2Mode(HazelcastClusteringAgent.java:288)
	at org.wso2.carbon.core.clustering.hazelcast.HazelcastClusteringAgent.loadHazelcastConfig(HazelcastClusteringAgent.java:334)
	at org.wso2.carbon.core.clustering.hazelcast.HazelcastClusteringAgent.init(HazelcastClusteringAgent.java:124)
	at org.wso2.carbon.core.util.ClusteringUtil.enableClustering(ClusteringUtil.java:38)
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.completeInitialization(StartupFinalizerServiceComponent.java:177)
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.serviceChanged(StartupFinalizerServiceComponent.java:288)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.registerThrottlingAgent(ThrottlingAgentServiceComponent.java:123)
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.activate(ThrottlingAgentServiceComponent.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:514)
	at org.wso2.carbon.core.init.CarbonServerManager.start(CarbonServerManager.java:219)
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.activate(CarbonCoreServiceComponent.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.equinox.http.servlet.internal.Activator.registerHttpService(Activator.java:81)
	at org.eclipse.equinox.http.servlet.internal.Activator.addProxyServlet(Activator.java:60)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.init(ProxyServlet.java:40)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.init(DelegationServlet.java:38)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1282)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1195)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1085)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5318)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5610)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1572)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1562)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.membership.scheme.kubernetes.exceptions.KubernetesMembershipSchemeException: Could not connect to Kubernetes API
	at org.wso2.carbon.membership.scheme.kubernetes.KubernetesMembershipScheme.connectAndRead(KubernetesMembershipScheme.java:280)
	at org.wso2.carbon.membership.scheme.kubernetes.KubernetesMembershipScheme.findContainerIPs(KubernetesMembershipScheme.java:204)
	at org.wso2.carbon.membership.scheme.kubernetes.KubernetesMembershipScheme.init(KubernetesMembershipScheme.java:159)
	... 80 more
Caused by: javax.net.ssl.SSLException: Received fatal alert: protocol_version
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1979)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1086)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.wso2.carbon.membership.scheme.kubernetes.api.KubernetesApiEndpoint.read(KubernetesApiEndpoint.java:43)
	at org.wso2.carbon.membership.scheme.kubernetes.KubernetesMembershipScheme.connectAndRead(KubernetesMembershipScheme.java:278)
	... 82 more
```

It seems related with SSL protocol version. Do you have any clue on how to solve that?

Thanks.

**Comment by faxioman** [comment]
Just for info, we resolve patching the constructor and recompiling the kube-membership java library and creating a "kubectl proxy" pod as kubernetes API endpoint.

**Comment by memorais** [comment]
Thanks for your feedback @faxioman .

The problem was related with Java version. In Java version 7 the default https protocol is TLSv1, after change to Java 8 which the default https protocol is TLSv1.2, it worked!

**Comment by chamilad** [comment]
@memorais I was able to workaround this in Java7 with the following parameters.

```
-Ddeployment.security.SSLv2Hello=false \
-Ddeployment.security.SSLv3=false \
-Ddeployment.security.TLSv1=false \
-Ddeployment.security.TLSv1.1=true \
-Ddeployment.security.TLSv1.2=true \
```

**Comment by memorais** [comment]
@chamilad Thanks!

**Comment by imesh** [comment]
@faxioman, @memorais I'm resolving this issue as the above workaround has solved this problem. Please feel free to reopen if you need further clarifications. Thanks
